import { Bot, User } from 'lucide-react';
import { Avatar, AvatarFallback } from '@/components/ui/avatar';

interface AuthorBioProps {
  authorName?: string;
  isVerified?: boolean;
  className?: string;
}

const AuthorBio = ({ authorName = 'MySankey Editorial Team', isVerified = false, className }: AuthorBioProps) => {
  return (
    <div className={`flex items-center gap-3 p-4 rounded-lg bg-muted/30 border border-border/30 ${className}`}>
      <Avatar className="w-10 h-10">
        <AvatarFallback className="bg-primary/10 text-primary">
          {isVerified ? <User className="w-5 h-5" /> : <Bot className="w-5 h-5" />}
        </AvatarFallback>
      </Avatar>
      <div>
        <p className="text-sm font-medium text-foreground">
          {isVerified ? `Generated by MySankey AI, reviewed by ${authorName}` : 'Generated by MySankey AI'}
        </p>
        <p className="text-xs text-muted-foreground">
          {isVerified 
            ? 'This flow has been editorially reviewed for accuracy' 
            : 'AI-generated visualization based on available data'}
        </p>
      </div>
    </div>
  );
};

export default AuthorBio;
