import { useState, useEffect } from 'react';
import { Loader2, Sparkles, BookOpen } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { supabase } from '@/integrations/supabase/client';
import type { SankeyData } from '@/types/sankey';

interface FlowAnalysisProps {
  title: string;
  data: SankeyData;
}

const FlowAnalysis = ({ title, data }: FlowAnalysisProps) => {
  const [analysis, setAnalysis] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const generateAnalysis = async () => {
    setIsLoading(true);
    setError(null);

    try {
      const nodeNames = data.nodes.map((n) => n.name);

      const { data: responseData, error: fnError } = await supabase.functions.invoke(
        'generate-flow-content',
        {
          body: {
            title,
            nodeNames,
            unit: data.unit,
            type: 'analysis',
          },
        }
      );

      if (fnError) {
        throw new Error(fnError.message || 'Failed to generate analysis');
      }

      if (responseData.error) {
        throw new Error(responseData.error);
      }

      setAnalysis(responseData.content);
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Failed to generate analysis';
      setError(message);
      console.error('Analysis generation error:', err);
    } finally {
      setIsLoading(false);
    }
  };

  // Auto-generate on mount
  useEffect(() => {
    generateAnalysis();
  }, [title]);

  return (
    <section className="mt-12 pt-8 border-t border-border/50">
      <div className="flex items-center gap-3 mb-6">
        <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
          <BookOpen className="w-5 h-5 text-primary" />
        </div>
        <div>
          <h2 className="text-xl font-semibold text-foreground">Analysis</h2>
          <p className="text-sm text-muted-foreground">AI-powered insights about this flow</p>
        </div>
      </div>

      {isLoading ? (
        <div className="bg-muted/30 rounded-xl p-8 text-center">
          <Loader2 className="w-8 h-8 text-primary animate-spin mx-auto mb-3" />
          <p className="text-muted-foreground">Generating analysis...</p>
        </div>
      ) : error ? (
        <div className="bg-destructive/10 rounded-xl p-6">
          <p className="text-destructive text-sm mb-4">{error}</p>
          <Button variant="outline" size="sm" onClick={generateAnalysis}>
            Try Again
          </Button>
        </div>
      ) : analysis ? (
        <div className="bg-muted/30 rounded-xl p-6 md:p-8">
          <div className="prose prose-sm dark:prose-invert max-w-none">
            <p className="text-foreground leading-relaxed whitespace-pre-wrap">{analysis}</p>
          </div>
          <div className="mt-6 pt-4 border-t border-border/50 flex items-center gap-2 text-xs text-muted-foreground">
            <Sparkles className="w-3.5 h-3.5" />
            <span>Generated by AI based on the flow structure</span>
          </div>
        </div>
      ) : null}
    </section>
  );
};

export default FlowAnalysis;
